In [1]:
import numpy as np

In [3]:
# ?np # présentation ou aide en ligne

In [4]:
print(np.sctypes)

{'int': [<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.int64'>], 'uint': [<class 'numpy.uint8'>, <class 'numpy.uint16'>, <class 'numpy.uint32'>, <class 'numpy.uint64'>], 'float': [<class 'numpy.float16'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.longdouble'>], 'complex': [<class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.clongdouble'>], 'others': [<class 'bool'>, <class 'object'>, <class 'bytes'>, <class 'str'>, <class 'numpy.void'>]}


In [5]:
status = np.array( [True, False])

In [6]:
status.dtype

dtype('bool')

In [7]:
status[0] = 9.0

In [8]:
status

array([ True, False])

In [9]:
status[0] = 0

In [10]:
status

array([False, False])

In [11]:
status + status

array([False, False])

In [12]:
2*status

array([0, 0])

In [13]:
status

array([False, False])

In [15]:
np.array([1, 2, np.nan], dtype='float64')

array([ 1.,  2., nan])

In [17]:
a = np.array(["Big data", "Python", "Pandas"])

In [18]:
a[0] = "Bonjour avez vous trouver une alternance ?"

In [19]:
a

array(['Bonjour ', 'Python', 'Pandas'], dtype='<U8')

In [20]:
dt = np.dtype([
    ('name', np.dtype('U14')), ('grades', np.float64) 
])

In [21]:
dataset = np.array([
      ( "Luce du Coulon" , 12.5),
      ( "Auguste Dupont", 8.5),
      ( "Roger Le Voisi", 1.5)
], dtype=dt)

In [22]:
dataset

array([('Luce du Coulon', 12.5), ('Auguste Dupont',  8.5),
       ('Roger Le Voisi',  1.5)],
      dtype=[('name', '<U14'), ('grades', '<f8')])

In [25]:
np.array([1, 2, 125], dtype='int8')

array([  1,   2, 125], dtype=int8)

In [27]:
np.array([1, 2, 400], dtype='int8')

/tmp/ipykernel_415/1680600612.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 400 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([1, 2, 400], dtype='int8')


array([   1,    2, -112], dtype=int8)

In [29]:
np.zeros(3).dtype

dtype('float64')

In [31]:
s = np.zeros((2,2))

In [32]:
s[0,0] = 1

In [33]:
s

array([[1., 0.],
       [0., 0.]])

In [34]:
collections = np.empty(10)

In [35]:
collections

array([4.64805205e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.76036810e-076, 9.04779959e-043, 5.88755624e-091,
       3.92587601e-033, 4.50885250e-315])

In [36]:
# Création de tableau
data = np.zeros(10)

In [37]:
data = data + 1

In [38]:
data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.random.randint(1, 100)

83

In [ ]:
# Exercice faire un algorithme qui rempli le tableau data de valeurs aléatoires