In [1]:
import numpy as np

In [3]:
january = np.array([-2,  5, -5,  6, -2,  0,  6,  2,  8,  0,  6, -1,  3,  3,  7,  0, -5,
        7,  4,  7,  8, -1,  5, -2,  3, -3, -2,  7,  8,  4,  2], dtype='float64')


In [5]:
# 1. Donnez toutes les températures qui sont supérieures à 0.

print( january[january > 0] )

[5. 6. 6. 2. 8. 6. 3. 3. 7. 7. 4. 7. 8. 5. 3. 7. 8. 4. 2.]


In [7]:
# 2. Comparez les températures supérieures et inférieures à 0.

print( ( january > 0 ).sum() > ( january <= 0 ).sum()  )

True


In [11]:
# 3. Donnez le pourcentage des températures positives sur le mois.

print( np.round( (january > 0 ).sum() / january.size, 2 ) * 100 )

61.0


In [14]:
# 4. Créez un tableau days pour les jours du mois et 
# donnez les jours pour lesquels la température était supérieure à 0.

days = np.arange( 1, january.size + 1 )

# print( days )

daysSupZero = days[ january > 0 ]
print(daysSupZero)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]
[ 2  4  7  8  9 11 13 14 15 18 19 20 21 23 25 28 29 30 31]


In [17]:
"""

5. Donnez toutes les températures supérieures à 0 
à partir du dixième jour du mois.

"""

print( january[ (days >= 10)  & ( january > 0 ) ] )

array([6., 3., 3., 7., 7., 4., 7., 8., 5., 3., 7., 8., 4., 2.])

In [20]:
"""

6. Remplacez maintenant les températures négatives par 
la moyenne des températures positives.

"""

# 1 médiane

median = np.median( january )
january[ january < 0 ] = median

print(january )

[3. 5. 3. 6. 3. 0. 6. 2. 8. 0. 6. 3. 3. 3. 7. 0. 3. 7. 4. 7. 8. 3. 5. 3.
 3. 3. 3. 7. 8. 4. 2.]
