In [1]:
import numpy as np

In [2]:
x1 = np.array([[9, 1, 2],
       [8, 0, 2],
       [5, 1, 5]])

In [4]:
x1.sum(1)

array([12, 10, 11])

In [5]:
x1.sum(0)

array([22,  2,  9])

In [6]:
prices = np.array([82, 92, 89, 65, 77, 66, 69, 65, 79, 51])

In [9]:
prices = prices*1.2

augmentation = lambda v : 1.2 *v 

augmentation(prices)

array([118.08, 132.48, 128.16,  93.6 , 110.88,  95.04,  99.36,  93.6 ,
       113.76,  73.44])